[versions]
appVersion = "0.1.0"
appVersionName = "0.1.0"
appId = "com.oldguy.kmpmarkup"

androidGradlePlugin = "9.0.0-alpha02"
javaVersion = "21"
androidBuildTools = "36.0.0"
androidSdk = "36"
androidSdkMinimum = "26"

kotlin = "2.2.10"
kotlinCoroutines = "1.10.2"
kotlinx-datetime = "0.7.1"

kmpIo = "0.3.0"
bigDecimal = "0.3.10"

dokkaPlugin = "2.0.0"
vannikTech = "0.34.0"

androidxTestRunner = "androidx.test.runner.AndroidJUnitRunner"
androidxTestRun = "1.7.0"
androidxJunit = "1.3.0"
androidxTestCore = "1.7.0"
junit5 = "5.13.4"
testMannodermausPlugin = "1.13.1.0"
testMannodermaus = "1.8.0"
testRunnerBuilder = "de.mannodermaus.junit5.AndroidJUnit5Builder"

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines"}
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

kmp-io = { module = "io.github.skolson:kmp-io", version.ref = "kmpIo" }
bigdecimal = { module = "com.ionspin.kotlin:bignum", version.ref = "bigDecimal"}

androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRun" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-runtime = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutines"}
mannodermaus-test = { module = "de.mannodermaus.junit5:android-test-core", version.ref = "testMannodermaus" }
mannodermaus-test-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "testMannodermaus" }

[bundles]
junit5-impl = [ "androidx-test-core", "junit5-api", "junit5-params", "mannodermaus-test" ]
junit5-runtime = [ "junit5-runtime", "androidx-test-runner", "mannodermaus-test-runner" ]
kotlin-test = [ "kotlin-test", "kotlin-test-annotations", "kotlinx-coroutines-test" ]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "testMannodermausPlugin" }
maven-publish-vannik = { id = "com.vanniktech.maven.publish", version.ref = "vannikTech" }
dokka-base = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
